### ISSUE TITLE
Tests still fail even with 0.7.2 on openSUSE (with python 2.7)

### ISSUE THREAD

**Issue by mcepl** [twisted/epsilon#30]
Thank you for fixing #25, but unfortunately we are still not there yet:
```
[    4s] ======================================================================
[    4s] ERROR: testProcessStartTimingCommand (epsilon.test.test_benchmark.BenchmarkProcessTestCase)
[    4s] testProcessStartTimingCommand
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
[    4s]     result = f(*args, **kw)
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
[    4s]     reraise(exc_info[1], exc_info[2])
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
[    4s]     result = f(*a, **kw)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.2/epsilon/test/test_benchmark.py", line 305, in setUp
[    4s]     spawnProcess)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.2/epsilon/scripts/benchmark.py", line 180, in spawn
[    4s]     proto = cls(d, filepath.FilePath(path))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.2/epsilon/scripts/benchmark.py", line 238, in __init__
[    4s]     self.partition = discoverCurrentWorkingDevice().split('/')[-1]
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.2/epsilon/scripts/benchmark.py", line 427, in discoverCurrentWorkingDevice
[    4s]     return possibilities[-1][-1]
[    4s] IndexError: list index out of range
[    4s] 
[    4s] ======================================================================
[    4s] ERROR: testProcessStopTimingCommand (epsilon.test.test_benchmark.BenchmarkProcessTestCase)
[    4s] testProcessStopTimingCommand
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
[    4s]     result = f(*args, **kw)
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
[    4s]     reraise(exc_info[1], exc_info[2])
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
[    4s]     result = f(*a, **kw)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.2/epsilon/test/test_benchmark.py", line 305, in setUp
[    4s]     spawnProcess)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.2/epsilon/scripts/benchmark.py", line 180, in spawn
[    4s]     proto = cls(d, filepath.FilePath(path))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.2/epsilon/scripts/benchmark.py", line 238, in __init__
[    4s]     self.partition = discoverCurrentWorkingDevice().split('/')[-1]
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.2/epsilon/scripts/benchmark.py", line 427, in discoverCurrentWorkingDevice
[    4s]     return possibilities[-1][-1]
[    4s] IndexError: list index out of range
[    4s] 
[    4s] ----------------------------------------------------------------------
[    4s] Ran 248 tests in 0.235s
```
What's wrong?

**Comment by mithrandi** [comment]
While I'm still interested to see exactly what is wrong here, I suspect it is some boring artifact of how the build/test environment or sandbox is constructed. #31 should fix this; I have released 0.7.3rc1 to make it easier for you to test this fix.

Assuming rc1 works for you, I will rerelease it as 0.7.3 with no changes.

**Comment by mcepl** [comment]
yes, with both patches from https://github.com/twisted/epsilon/pull/31 tests pass for me. Thank you.

**Comment by mcepl** [comment]
I really don't understand what happened. But it seems that the issue has returned even with 0.7.3 (sha1 of the tarball is `71ead419634626e8d294f61778fa4af49875b23b`). Full 
[build log](https://github.com/twisted/epsilon/files/2630315/osc-build-log.txt) is here, but the relevant part IMHO is:

```
[    4s] ======================================================================
[    4s] ERROR: testProcessStartTimingCommand (epsilon.test.test_benchmark.BenchmarkProcessTestCase)
[    4s] testProcessStartTimingCommand
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
[    4s]     result = f(*args, **kw)
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
[    4s]     reraise(exc_info[1], exc_info[2])
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
[    4s]     result = f(*a, **kw)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/test/test_benchmark.py", line 305, in setUp
[    4s]     spawnProcess)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 180, in spawn
[    4s]     proto = cls(d, filepath.FilePath(path))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 243, in __init__
[    4s]     self.overallChange.start(self.path, self.disk, self.partition)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 205, in start
[    4s]     beforeDiskStats = captureStats()
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 73, in captureStats
[    4s]     return dict(parseDiskStats(file('/proc/diskstats')))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 64, in parseDiskStats
[    4s]     yield parseDiskStatLine(L)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 54, in parseDiskStatLine
[    4s]     return device, factory(*map(int, parts[3:]))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/structlike.py", line 77, in __init__
[    4s]     (len(args), len(self.__names__)))
[    4s] TypeError: Got 15 positional arguments but expected no more than 11
[    4s] 
[    4s] ======================================================================
[    4s] ERROR: testProcessStopTimingCommand (epsilon.test.test_benchmark.BenchmarkProcessTestCase)
[    4s] testProcessStopTimingCommand
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
[    4s]     result = f(*args, **kw)
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
[    4s]     reraise(exc_info[1], exc_info[2])
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
[    4s]     result = f(*a, **kw)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/test/test_benchmark.py", line 305, in setUp
[    4s]     spawnProcess)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 180, in spawn
[    4s]     proto = cls(d, filepath.FilePath(path))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 243, in __init__
[    4s]     self.overallChange.start(self.path, self.disk, self.partition)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 205, in start
[    4s]     beforeDiskStats = captureStats()
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 73, in captureStats
[    4s]     return dict(parseDiskStats(file('/proc/diskstats')))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 64, in parseDiskStats
[    4s]     yield parseDiskStatLine(L)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 54, in parseDiskStatLine
[    4s]     return device, factory(*map(int, parts[3:]))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/structlike.py", line 77, in __init__
[    4s]     (len(args), len(self.__names__)))
[    4s] TypeError: Got 15 positional arguments but expected no more than 11
[    4s] 
[    4s] ======================================================================
[    4s] ERROR: testCaptureStats (epsilon.test.test_benchmark.DiskstatTestCase)
[    4s] testCaptureStats
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
[    4s]     result = f(*args, **kw)
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
[    4s]     reraise(exc_info[1], exc_info[2])
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
[    4s]     result = f(*a, **kw)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/test/test_benchmark.py", line 109, in testCaptureStats
[    4s]     stats = benchmark.captureStats()
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 73, in captureStats
[    4s]     return dict(parseDiskStats(file('/proc/diskstats')))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 64, in parseDiskStats
[    4s]     yield parseDiskStatLine(L)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 54, in parseDiskStatLine
[    4s]     return device, factory(*map(int, parts[3:]))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/structlike.py", line 77, in __init__
[    4s]     (len(args), len(self.__names__)))
[    4s] TypeError: Got 15 positional arguments but expected no more than 11
[    4s] 
[    4s] ======================================================================
[    4s] ERROR: testStart (epsilon.test.test_benchmark.SnapshotTestCase)
[    4s] testStart
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
[    4s]     result = f(*args, **kw)
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
[    4s]     reraise(exc_info[1], exc_info[2])
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
[    4s]     result = f(*a, **kw)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/test/test_benchmark.py", line 416, in testStart
[    4s]     c.start(filepath.FilePath('.'), 'hda', 'hda1')
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 205, in start
[    4s]     beforeDiskStats = captureStats()
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 73, in captureStats
[    4s]     return dict(parseDiskStats(file('/proc/diskstats')))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 64, in parseDiskStats
[    4s]     yield parseDiskStatLine(L)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 54, in parseDiskStatLine
[    4s]     return device, factory(*map(int, parts[3:]))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/structlike.py", line 77, in __init__
[    4s]     (len(args), len(self.__names__)))
[    4s] TypeError: Got 15 positional arguments but expected no more than 11
[    4s] 
[    4s] ======================================================================
[    4s] ERROR: testStop (epsilon.test.test_benchmark.SnapshotTestCase)
[    4s] testStop
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
[    4s]     result = f(*args, **kw)
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
[    4s]     reraise(exc_info[1], exc_info[2])
[    4s]   File "/usr/lib64/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
[    4s]     result = f(*a, **kw)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/test/test_benchmark.py", line 422, in testStop
[    4s]     c.stop(filepath.FilePath('.'), 'hda', 'hda1')
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 218, in stop
[    4s]     afterDiskStats = captureStats()
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 73, in captureStats
[    4s]     return dict(parseDiskStats(file('/proc/diskstats')))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 64, in parseDiskStats
[    4s]     yield parseDiskStatLine(L)
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/scripts/benchmark.py", line 54, in parseDiskStatLine
[    4s]     return device, factory(*map(int, parts[3:]))
[    4s]   File "/home/abuild/rpmbuild/BUILD/Epsilon-0.7.3/epsilon/structlike.py", line 77, in __init__
[    4s]     (len(args), len(self.__names__)))
[    4s] TypeError: Got 15 positional arguments but expected no more than 11
[    4s] 
[    4s] ----------------------------------------------------------------------
[    4s] Ran 249 tests in 0.202s
[    4s] 
[    4s] FAILED (errors=5, skipped=5)
```
Any idea, what's going on?
